sudo: required
services:
  - docker

before_install:
  - docker build -t pedro412/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pedro412/react-test npm test

after_success:
  - docker build -t pedro412/multi-client ./client
  - docker build -t pedro412/multi-nginx ./nginx
  - docker build -t pedro412/multi-server ./server
  - docker build -t pedro412/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push pedro412/multi-client
  - docker push pedro412/multi-nginx
  - docker push pedro412/multi-server
  - docker push pedro412/multi-worker
